### ISSUE TITLE
File size failure should happen first

### ISSUE THREAD

**Issue by rmenessec** [doomedraven/VirusTotalApi#11]
Given this:
```
john@malkovich ~ $ vt -v -f test.txt

Calculating hash for: test.txt
[!] Ignored file: test.txt, size is to big, permitted size is 128Mb
```
vt should fail on file size first, and not bother to calculate the hash.

**Comment by doomedraven** [comment]
I prefer not spam vt with big files as they willl be rejected in any way

**Comment by rmenessec** [comment]
I'm asking if vt can fail more gracefully in this case, without wasting a lot of CPU time. I'm using vt in a case where I don't always have control over the input files.

**Comment by doomedraven** [comment]
what you mean more gracefully exactly?, it use less cpu with prechecking size, instead of upload a big file to vt and vt rejects it, so it would be wasting of your time and vt

**Comment by rmenessec** [comment]
Before vt rejects the file, it calculates the hash. I'm asking if you can move the file size check in front of the hash computation.

**Comment by doomedraven** [comment]
make sense, I will push update  it probably in few hours

**Comment by rmenessec** [comment]
Thanks !

**Comment by doomedraven** [comment]
done, https://github.com/doomedraven/VirusTotalApi/commit/72b7fcfe752c120473ee5ab46c23cff2b025eadb

the pip will be updated later

**Comment by doomedraven** [comment]
thanks
