### ISSUE TITLE
Can't resolv hostname

### ISSUE THREAD

**Issue by c0r3dump3d** [doomedraven/VirusTotalApi#12]
Hi, when I try to send a file to scan to Virustotal with the option -f I have this error:

`Can't resolv hostname, check your internet conection`

My internet connection it's fine and when I use the script with the option -fs, to obtain only the report, it's work fine.

Thank's

**Comment by doomedraven** [comment]
with -f works fine here, it can be related to vt api server side problems as I saw it too, the error which trigger that msg is:
`except requests.exceptions.ConnectionError:`

so it related to their side too, can you try during today and let me know if issue still persist, i will close it as in not 100% my side problem, but i need to improve error msg

**Comment by c0r3dump3d** [comment]
Ok, thank's for your fast  answer, I will try during today.

**Comment by c0r3dump3d** [comment]
Sorry for the insistence but the error persists. Do you know if Virustotal has problem with the service or perhaps it is problem of my api key?

**Comment by doomedraven** [comment]
If tou can do any other request it not your side problem, probably some problems on their side, as in past we saw problem in some countries, not in all, try increase timeout in config, i dont thing it will change something but who knows

**Comment by doomedraven** [comment]
is that issue still persist for you?

**Comment by c0r3dump3d** [comment]
Hi, yes the issue persist. I have wrote to Virustotal but they have not answered me. I think it's problem of my API key ...

**Comment by c0r3dump3d** [comment]
Now Virustotal  answered me and say this:

"We had some connectivity issues a few days ago. Now all is working correctly."

But it's not working ...

**Comment by doomedraven** [comment]
yes as I told we saw that in past, it also can be related to geo related load, as here it works just fine

**Comment by c0r3dump3d** [comment]
Hi, the issue it has been fixed!!

Thank you for your attention.

**Comment by doomedraven** [comment]
what it was? vt side?

**Comment by c0r3dump3d** [comment]
Yes, it was in the side of vt.

**Comment by doomedraven** [comment]
i'm happy what everything solved. if you have any suggestion/issues with my api client feel free to tellme to improve it :)
