### ISSUE TITLE
misspelling

### ISSUE THREAD

**Issue by LouAlbano** [doomedraven/VirusTotalApi#13]
Minor issue, you have a misspelling: 

~/testids/VirusTotalApi/vt$ fgrep -R 'few minuts'
vt.py:                        print '[+] Check rescan result with sha256 in few minuts : \n\tSHA256 : {sha256}'.format(sha256=jdata['sha256'])
vt3.py:                        print('[+] Check rescan result with sha256 in few minuts : \n\tSHA256 : {sha256}'.format(sha256=jdata['sha256']))

**Comment by doomedraven** [comment]
Thanks :)
going to fix it, feel free push PR also
