### ISSUE TITLE
search and download files by query

### ISSUE THREAD

**Issue by nirizr** [doomedraven/VirusTotalApi#14]
I'd like to download files fetched using a query string (similarly to the way described [here](https://www.virustotal.com/en/documentation/private-api/#search) using a search modifier (and not just hashes) and download all (or some) matching files.

Doing so from the command line as VirusTotalApi allows would be most convenient for me and I assume others as well.

**Comment by doomedraven** [comment]
hello
I have it in ToDo :) i will add this ASAP
should be implemented this days

**Comment by nirizr** [comment]
Wow, thanks for the prompt reply!

Awesome :)

**Comment by doomedraven** [comment]
thanks for use it :)

**Comment by doomedraven** [comment]
done, you can pass `-dl` to download all that hashes, + you can use `-dt x` to specify number of threads to download, by default 5

**Comment by nirizr** [comment]
Cheers!
