### ISSUE TITLE
bulk domain scan

### ISSUE THREAD

**Issue by SuchitV** [doomedraven/VirusTotalApi#16]
is there a built in option to scan a large list of domains in a file?

**Comment by doomedraven** [comment]
`vt -d domain1 domain2`try it ;) see options for more info to filter it as by default it not show nothing `-v` will return all info for them

**Comment by SuchitV** [comment]
I'm able to do that but I meant is it possible to do vt -d
filelistofdomains.txt

**Comment by doomedraven** [comment]
No, but it easy to add, will try to add it in a bit :) i will let you know once that is done

**Comment by SuchitV** [comment]
Thanks.. I appreciate it.

Suchit

**Comment by doomedraven** [comment]
done, already in repo or you can install it with `sudo pip install vt -U`
thanks :)

let me know if you have more feature requests or anything :)
