### ISSUE TITLE
--distribution-files not working

### ISSUE THREAD

**Issue by threatlead** [doomedraven/VirusTotalApi#17]
Getting following error when trying to use distribution-files option. Could someone please provide an example of its usage? It seems to be expecting an argument and I tried using 'distribution options' like after/before/reports/etc. but it didn't worked. I am using the most recent version=1.0.7.8

```
$>vt --distribution-files -v
[!] You need to provide some arguments
```

**Comment by doomedraven** [comment]
@threatlead thanks for reporting, resolved :) packet for pip is not updated, because i need check other stuff, in private part, but you can download from here and install it :)
