### ISSUE TITLE
Error while executing

### ISSUE THREAD

**Issue by VikramKharvi** [doomedraven/VirusTotalApi#17]
Traceback (most recent call last):
  File "vt.py", line 3204, in <module>
    main()
  File "vt.py", line 3122, in main
    vt.url_scan_and_report(**options)
  File "vt.py", line 1703, in url_scan_and_report
    if len(urls) > end + increment:
NameError: global name 'urls' is not defined

**Comment by doomedraven** [comment]
thanks for the report, can you pass me the command how you got it ? to test the fix :)

**Comment by doomedraven** [comment]
fixed ;) updated in repo, i will release pip package later, thanks
