### ISSUE TITLE
Initialization of the script

### ISSUE THREAD

**Issue by hakija** [doomedraven/VirusTotalApi#18]
The manual says: "Before using the tool you must set your api key near the end of the file or in ~.vtapi."

Tried both, and did not manage to get it to work. Can you please alaborate on how to do this?
EG. I chnaged the lines 1738 and 1739 but allways get an error, either invalid synthax or global name 'private' is not defined. Can you specifiy exsactly how to enter the VT API...

Also, created a XX.vtapi file in my user root, but the script cant find it? Some explanation on that also please?

I found what seams al older version of the script at: http://pastebin.com/kR5z070t but this one hase cleary marked where to enter your VT API and everything works!

Sorry for this noob questions and thak you for a great script!

**Comment by doomedraven** [comment]
@hakija 
now is only support this way to setup now:

Before using the tool you must set your api key in $HOME/.vtapi

$HOME/.vtapi file content:
```
[vt]
apikey=your-apikey-here
type=private
intelligence=False
```

which OS you use? This example if for linux

**Comment by hakija** [comment]
I'm using Win10 and Win 7...that would explain the problems I'm having...
Can you please give some instruction on how to use it in Win if possible?

No way of "hard coding" the API within the scrip as in previous version I mention?

**Comment by doomedraven** [comment]
i don't have windows here to try it, but simple and very quick solution is this,
Download as zip or clone in desktop, then open file in vt with the name vt.py and
change this [code](https://github.com/doomedraven/VirusTotalApi/blob/master/vt/vt.py#L1898)

from line 1898, take care about spaces, but you only need hardcode it in first line of this code and comment the conf file read/parse, or better to avoid errors remove it, just leave first lines with apikey, api_type and intelligence
```
    apikey = None # put here you aqui key
    api_type = False
    intelligence = False
    """
    try:
        confpath = os.path.expanduser('~/.vtapi')
        if os.path.exists(confpath):
            config = ConfigParser.RawConfigParser()
            config.read(confpath)
            if config.has_option('vt', 'apikey'):
                apikey = config.get('vt', 'apikey')
                if config.has_option('vt', 'type'):
                   api_type = config.get('vt', 'type')

                   if  api_type.lower() == 'private':
                        api_type = True
                   else:
                        api_type = False

                if config.has_option('vt', 'intelligence'):
                    intelligence = config.get('vt', 'intelligence')
        else:
            sys.exit('\nFile {0} don\'t exists\n'.format(confpath))

    except Exception:
        sys.exit('''
        No API key provided or cannot read ~ /.vtapi. Specify an API key in ~ /.vtapi.
        Format:
            [vt]
            apikey=your-apikey-here
            type=public #private if you have private api
            intelligence=False # True if you have access
        For more information check:
            https://github.com/doomedraven/VirusTotalApi
    '''
        )
    """
```

in this way you will hardcode the data, once i will have access to windows i will get a look on it
hope it helps to you

**Comment by hakija** [comment]
Hi,

ok, this worked! I only had to leave the api_type = False. The instruction mention to set it to public or blank but then I get an error. I dont know if is ok or not...

Now I just have to try some analyzing to check if I run into any issues...

Thank you for prompt response and help!!

**Comment by doomedraven** [comment]
@hakija you are welcome, i just added some stuff, you can have file created as 
__.vtapi__ or __vtapi.conf__ in your user home dirrectory, this might be useful for windows as probably windows don't permit create name which starts with dot

**Comment by doomedraven** [comment]
i will close it, if you will have issue reopen it
