### ISSUE TITLE
Error still persist.

### ISSUE THREAD

**Issue by VikramKharvi** [doomedraven/VirusTotalApi#19]
vikram@vikram:~/VirusTotalApi/vt$ python vt.py -ur google.com virustotal.com
Traceback (most recent call last):
  File "vt.py", line 3203, in <module>
    main()
  File "vt.py", line 3130, in main
    vt.url_scan_and_report(**options)
  File "vt.py", line 1725, in url_scan_and_report
    print '\nSearching for url(s) report: \n\t{url}'.format(url=url_upload.replace(', ', '\n\t'))
AttributeError: 'list' object has no attribute 'replace'

**Comment by doomedraven** [comment]
thanks for reporting, should be fixed now :)
btw please stay with one issue even if that one is closed
