### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by E3V3A** [doomedraven/VirusTotalApi#20]
It would be profitable for your project to show some screenshots of how the results look.
(The doomedraven manual does load pictures for some reason.)

**Comment by doomedraven** [comment]
Well that would be more nice but normally to show the power of it i would need to show a lot of data, i will think how to update readme to reflect that :)

Thanks for idea. Let me know if you have more

**Comment by E3V3A** [comment]
I think even one picture showing the results for one file would suffice. It's just a PITA to have to go through your source code to try to figure out if it's worth cloning. (Yeah, sorry, but there are several dozens of VT py scripts out there.) I like yours because it doesn't add a bunch of bloated dependencies, which are often broken under Windows for example.

**Comment by doomedraven** [comment]
agree, but as I told it returns too much info to show, I will get some nice piece and put it there, is why I put the `--help` in readme to show all supported stuff :)
