### ISSUE TITLE
No result on -rai

### ISSUE THREAD

**Issue by juanandresgs** [doomedraven/VirusTotalApi#23]
Hey! Thanks for the great script.
I'm getting results when I use -s <hash> but when any attempts at using the -rai option come up empty. Have tried all of the following with no results.
vt -s -rai <hash> 
vt -s --report-all-info <hash>
vt -rai <hash> 
vt --report-all-info <hash>

**Comment by doomedraven** [comment]
try adding `-v`, as by default output is disabled to be able show only what we want from rai or any other part, also if that doesnt work, can you provide any hash/url which do you check to verify :)

**Comment by juanandresgs** [comment]
That worked! Thank you :)
