### ISSUE TITLE
Using behind corp proxy

### ISSUE THREAD

**Issue by syloktools** [doomedraven/VirusTotalApi#30]
How would you suggest modifying this to support using it behind a proxy?

**Comment by doomedraven** [comment]
hello, add to kwargs `proxies={"http":X, "https":X}`
here https://github.com/doomedraven/VirusTotalApi/blob/master/vt/vt.py#L817

i will add support to this next week

**Comment by doomedraven** [comment]
sorry for huge delay, added support for it, you can specify it adding proxy=http.... in config or set env variable PROXY=X vt .....

let me know if that works

**Comment by doomedraven** [comment]
reopen if required
