### ISSUE TITLE
Certain type of files crushes the tool 

### ISSUE THREAD

**Issue by 4wa** [doomedraven/VirusTotalApi#33]
I'm scanning a folder of 1000 binaries. However, I have noticed that certain types of files cause the tool to crush and give the same error massage. 

Error Massage 

```
Traceback (most recent call last):
  File "C:\Users\A\Anaconda2\Lib\site-packages\vt\vt.py", line 3760, in <module>
    main()
  File "C:\Users\A\Anaconda2\Lib\site-packages\vt\vt.py", line 3667, in main
    vt.fileScan(**options)
  File "C:\Users\A\Anaconda2\Lib\site-packages\vt\vt.py", line 2045, in fileScan
    result = self.getReport(**kwargs)
  File "C:\Users\A\Anaconda2\Lib\site-packages\vt\vt.py", line 930, in getReport
    hashes_report = hashlib.sha256(open(hashes_report, 'rb').read()).hexdigest()
IOError: [Errno 22] invalid mode ('rb') or filename: 'C:\\Users\\A\\Downloads\\Binaries\\3000\\532b923cbfe56c4225b163bcc8f44a076c2853a556f11c832225b3d3a56fa3ac'
``` 

Examples: 

SHA-256    67bf7969abe5ada19e78c8f3090eb8cfa3bab3c4ffc585ac5b8ad5f113ebff2f
SHA-256    2eb7912fc2bae52e035b26a70c1b846fbf544cfb08f098847d2630c927fc6cbc

All are:
Magic	PE32 executable for MS Windows (GUI) Intel 80386 32-bit

Also some files end up being deleted from the folder after running the tool. 
such as:

SHA-256 | 4a56bd3af6df1246286b9eebfd055cc060851e71346709628d3ff72175085693
SHA-256 | 4d26aff3a73f49423aad2fa6eb2b7b7dcd6af918c1b1e9b89115e9928963b7b8

Is there any logical reason behind such occurrence?

**Comment by doomedraven** [comment]
Hey thanks for reporting it, no, can you please post how ypu exec it + vt -V

**Comment by 4wa** [comment]
Since I want the json files I use this:

Python C:\Users\A\Anaconda2\Lib\site-packages\vt\vt.py -f C:\Users\A\Downloads\Binaries\3000 --dump

**Comment by doomedraven** [comment]
thanks i will check that asap

**Comment by doomedraven** [comment]
the daleted part not make sense, there nothing what could remove them
the other one is interesting

**Comment by doomedraven** [comment]
im closing this as i wasn't able to reproduce it, let me know if you still see this issue in latest version
