### ISSUE TITLE
config creation in py3 broken

### ISSUE THREAD

**Issue by doomedraven** [doomedraven/VirusTotalApi#34]

**Comment by ilovemilk** [comment]
Hi, 
not only py3 also python 2.7.1.
See the following trace.

`[+] You have access to VT intelligence True/False: True  
Traceback (most recent call last):  
  File "vt/vt.py", line 3380, in <module>  
    main()  
  File "vt/vt.py", line 3129, in main  
    vt_config = read_conf()  
  File "vt/vt.py", line 3087, in read_conf  
    config_file = create_config_file(paths)  
  File "vt/vt.py", line 3028, in create_config_file  
    conf_template = conf_template % (apikey.encode(), type_key.encode(), intelligence.encode())  
ValueError: unsupported format character 'b' (0x62) at index 14`

Best regards
ilovemilk

**Comment by doomedraven** [comment]
oh damn, thanks for letting me know, i will try to fix it today

**Comment by doomedraven** [comment]
can you please test last commit, works in local, i hope to think on solution to handle both versions today

**Comment by ilovemilk** [comment]
Works perfectly! Thanks for the fast fix.

**Comment by doomedraven** [comment]
thanks for catch it and feedback :)
