### ISSUE TITLE
Wrong Time Format

### ISSUE THREAD

**Issue by KlausItem** [doomedraven/VirusTotalApi#37]
Hello,

i got a Problem with te result of creation Time. See example:

                                                                             
  last_submission_date   2019-04-27 20:10:27                                                             
         creation_date   1.420e+09                                                                       
        unique_sources   206                                                                             
 first_submission_date   2015-01-12 23:53:44                                                             
      type_description   Win32 EXE                                                                       
            reputation   116                                                                             
last_modification_date   2019-04-28 16:55:28                                                             
              type_tag   peexe                                                                           
                ssdeep   1

Any idea ???

**Comment by doomedraven** [comment]
hey, thanks for reporting, can you post which command did you exec to reproduce that easilly?

**Comment by doomedraven** [comment]
ah i see

**Comment by doomedraven** [comment]
thanks again for reporting it :) let me know if you find any

```
         Name                                                 Value
=========================================================================================================
                  size   88576
          authentihash   40cf9e20a70e31f22a5c0b92a3c58fbafceb662dd8762b477f0817915ba05d0a
                  sha1   8fef2c2bc87ef7d135296fdb4cf9ecd9c0322d55
                 magic   PE32 executable for MS Windows (console) Intel 80386 32-bit
                 vhash   0840876d15551c0d5d1d1038z2e02fz12z18fz
    last_analysis_date   2019-04-27 20:10:27
       meaningful_name   cmdow.exe
       times_submitted   236
  last_submission_date   2019-04-27 20:10:27
         creation_date   2014-12-30 12:08:55 <--------------
        unique_sources   206 
 first_submission_date   2015-01-12 23:53:44
      type_description   Win32 EXE
            reputation   116
last_modification_date   2019-04-28 16:55:28
              type_tag   peexe
                ssdeep   1536:ufVX5SG8cD++OTJ5enxjSiXkSxf5DqWtp0XU1jDBBrjK8o3agdbx583+fs7k+nUI:O5SG7S6/7k
                         +nUwoL1xii2l8NXQUQUlC
                sha256   767b877e735c425bf05c34683356abfde4070b092f17a4741ea5ac490611f3de
           total_votes   {u'harmless': 11, u'malicious': 0}
                   md5   ddd12566b99343b96609afa2524ecec3
```
