### ISSUE TITLE
No such file or directory: 'VTDL_/home/a/Desktop...json'

### ISSUE THREAD

**Issue by 4wa** [doomedraven/VirusTotalApi#41]
When I run this command I get the following error:

`python /home/a/anaconda3/lib/python3.7/site-packages/vt/vt.py -f /home/a/Desktop/2018/part1/binaries/dealply --dump`

```
File "/home/a/anaconda3/lib/python3.7/site-packages/vt/vt.py", line 257, in jsondump
    jsondumpfile = open('VTDL_{name}.json'.format(name=sha1), 'w')

FileNotFoundError: [Errno 2] No such file or directory: 'VTDL_/home/a/Desktop/2018/part1/binaries/dealply/5824308a4e84fd3bfa16d555785751819dfac749c6aa95f11150601813d0e129.json
```

it seems like instead of getting the (name = sha1) it writes the path of the file?! 

I'm working on python Python 3.7.1 and ubuntu

**Comment by doomedraven** [comment]
Thanks for reporting, check latest commit, fixed now :) let me know if you see something else
