### ISSUE TITLE
Download from search not documented

### ISSUE THREAD

**Issue by malvidin** [doomedraven/VirusTotalApi#42]
Please describe the Search Intelligence / Download functionality in the help for the `-si` and `-dl`.

Because the [VirusTotal Top N Downloader](https://storage.googleapis.com/vtcdn/api-scripts/search_and_download_topn_files.py) failed, I used this package from PyPI (version 3.1.3.7). But I only found this capability when searching issues (#14); it is not documented in the help.

My draft help strings are below.

https://github.com/doomedraven/VirusTotalApi/blob/master/vt/vt.py#L3224
`Search query, can be paired with the download option. Search help can be found here - https://www.virustotal.com/intelligence/help/`

https://github.com/doomedraven/VirusTotalApi/blob/master/vt/vt.py#L3320
`The md5/sha1/sha256 hash of the file(s) you want to download. Can be space separated list of hashes to download, will save with hash as name. Alternatively provide txt file with .txt extension, with hashes, or hash and type, one by line, for example: hash,pcap or only hash. When paired with the search-intelligence option, downloads hashes returned from the search.`

**Comment by doomedraven** [comment]
Hey, thanks for headups, will update it

**Comment by doomedraven** [comment]
would this works?


opt.add_argument('-si', '--search-intelligence', action='store_true', help='Search query, help can be found here - https://www.virustotal.com/intelligence/help/, if you specify -dl option it will download all matched hashes')

**Comment by doomedraven** [comment]
updated them both, thanks again, let me know if you find any other issue
