### ISSUE TITLE
Build Version Mismatch

### ISSUE THREAD

**Issue by malvidin** [doomedraven/VirusTotalApi#43]
When creating the package for distribution, it uses the version from setup.py, not vt.py.

[setup.py.txt](https://github.com/doomedraven/VirusTotalApi/files/3901796/setup.py.txt)

**Comment by doomedraven** [comment]
fixed thanks

**Comment by malvidin** [comment]
Because the classifiers are static, the Development Statusis still listed as "5 - Production/Stable". In the code above, I used the "a" in the end of "4.0.0.0a3" to mark it "3 - Alpha", and so that it would change to "4 - Beta" if the version became "4.0.0.0b1".

**Comment by doomedraven** [comment]
well i did't see problem in my code, at least what im using on daily basis, and nobody reported any other, as their api v3 is still in dev, is kinda what they can break things, so i didn't change that, bcz if that would be my choice i would call it v4 already. so just think github repo is dev version, pip is stable

is why in pip you have latest stable version https://pypi.org/project/vt/ `vt 3.1.3.7` based on api v2 of vt
