### ISSUE TITLE
VirtusTotalAPI - ValueError: invalid literal for int() with base 10: '60 \t\t#default 60, if you want change it, specify number here'

### ISSUE THREAD

**Issue by redteamcaliber** [doomedraven/VirusTotalApi#7]
[root@localhost ~]# vt -h
Traceback (most recent call last):
  File "/usr/bin/vt", line 9, in <module>
    load_entry_point('vt==2.2.2', 'console_scripts', 'vt')()
  File "/usr/lib/python2.7/site-packages/vt-2.2.2-py2.7.egg/vt/vt.py", line 2883, in main
    req_timeout = int(vt_config.get('timeout'))
ValueError: invalid literal for int() with base 10: '60 \t\t#default 60, if you want change it, specify number here'

vim /usr/lib/python2.7/site-packages/vt-2.2.2-py2.7.egg/vt/vt.py 

2876
2877 def main():
2878
2879    vt_config = read_conf()
2880
2881    if vt_config.get('timeout'):
2882        global req_timeout
**2883        req_timeout = int(vt_config.get('timeout'))**
2884
2885   opt = argparse.ArgumentParser('value', description='Scan/Search/ReScan/JSON parse')

[root@localhost ~]# cat .vtapi.conf
[vt]
apikey= [ MY API KEY HERE ]
type=public
intelligence=False
engines=        #put there coma separated engine list, or only one, or leave it empty
**timeout=60        #default 60, if you want change it, specify number here**

[root@localhost ~]# cat .vtapi
[vt]
apikey= [ MY API KEY HERE ]
type=public
intelligence=False
engines=        #put there coma separated engine list, or only one, or leave it empty
**timeout=60        #default 60, if you want change it, specify number here**
# Misc:
- I correctly I configured the value for timeout variable in the configuration files for both root as a regular user. I used the physical and virtual machines and also python 2.x and 3.x, without success.
  -I used a commit of the day July 29, 2016 and was fucionando correctly.
- My both virtual environment as a physical are Fedora 23 and 24 x86_64 no case can only use this distro unfortunately at the moment.
# Fedora 24 x86_64

Linux localhost.localdomain 4.7.4-200.fc24.x86_64 #1 SMP Thu Sep 15 18:42:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.12
# Fedora 23 x86_64

Linux localhost.localdomain 4.7.4-100.fc23.x86_64+debug #1 SMP Thu Sep 15 18:31:53 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Python 2.7.11

Thansk, bro!

**Comment by doomedraven** [comment]
Can you try one thing? As i dont have that bug and many of my friend who use it also not have it
1. Try to leave in .vtapi only timeout=60
   Without commend after that
   If that not works
2. In this line 2883, replace 
   req_timeout = int(vt_config.get('timeout')) to 
   req_timeout = int(vt_config.get('timeout'), 60)

Let me know if that works, if not i will need deploy fedora and make tests. 

Tnx for reporting
Best regards

**Comment by doomedraven** [comment]
@redteamcaliber just tested
if you have comment after number of seconds in timeout, it breaks vt, change that and should works, changing readme :)
i had `timeout = 60` nothing else :D

**Comment by doomedraven** [comment]
closing as no response
