### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by mytts** [doomedraven/VirusTotalApi#8]
is there any plan to support python3?

**Comment by doomedraven** [comment]
yes i hope that will be done soon, initial work started few weeks ago, i hope have it soon, but i dont' have enough free time to finish if quickly

**Comment by doomedraven** [comment]
hey sorry for long delay, im doing this on my free time, i wasn't need of py3 support till today, so i expect it will be done pretty soon now, FYI
